name: Auto Merge Lyrics

on:
  push:
    paths:
      - 'datalake/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run parser & merge
        run: python -m scripts.main
      - name: Commit artists
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add artists/
          git commit -m "chore: auto update artists/ from datalake" || echo "no changes"
          git push
